name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Connected to EC2 successfully!"
            cd /home/ec2-user/CI-CD  # שינוי הנתיב לתיקיית הפרויקט שלך
            git pull origin main  # מושך עדכונים מה-Repo
           